In [24]:
from skimage import io
import matplotlib.pyplot as plt 
import tensorflow as tf
import numpy as np
import os

tf.get_logger().setLevel('ERROR')

def load_data(data_directory):
    directories = [d for d in os.listdir(data_directory)
                  if os.path.isdir(os.path.join(data_directory, d))]
    labels = []
    images = []
    
    for d in directories:
        label_directory = os.path.join(data_directory, d)
        file_names = [os.path.join(label_directory, f)
                     for f in os.listdir(label_directory)
                     if f.endswith(".png")]
        for f in file_names:
            images.append(io.imread(f))
            labels.append(int(d))
    return np.array(images), np.array(labels)

In [25]:
ROOT_PATH = "/Users/dfebles/Developer/machine-learning/shapes"
train_data_directory = os.path.join(ROOT_PATH, "training")
test_data_directory = os.path.join(ROOT_PATH, "testing")

train_images, train_labels = load_data(train_data_directory)
train_images = train_images / 255.0

test_images, test_labels = load_data(test_data_directory)
test_images = test_images / 255.0

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(24, 24)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(3)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=8)
model.evaluate(test_images, test_labels, verbose = 2)

Epoch 1/8
94/94 [==============================] - 0s 762us/step - loss: 1.0048 - accuracy: 0.5120
Epoch 2/8
94/94 [==============================] - 0s 769us/step - loss: 0.7660 - accuracy: 0.6503
Epoch 3/8
94/94 [==============================] - 0s 753us/step - loss: 0.7141 - accuracy: 0.6567
Epoch 4/8
94/94 [==============================] - 0s 779us/step - loss: 0.6191 - accuracy: 0.7173
Epoch 5/8
94/94 [==============================] - 0s 749us/step - loss: 0.5444 - accuracy: 0.7693
Epoch 6/8
94/94 [==============================] - 0s 778us/step - loss: 0.5027 - accuracy: 0.7877
Epoch 7/8
94/94 [==============================] - 0s 798us/step - loss: 0.4438 - accuracy: 0.8320
Epoch 8/8
94/94 [==============================] - 0s 799us/step - loss: 0.4054 - accuracy: 0.8557
19/19 - 0s - loss: 0.3750 - accuracy: 0.8783


[0.3749639093875885, 0.878333330154419]

In [26]:
probability_model = tf.keras.models.Sequential([
    model,
    tf.keras.layers.Softmax()
])

shapes = ['rectangle', 'ellipse', 'circle']
predictions = probability_model.predict(test_images)

print(np.argmax(predictions[0]))
print(predictions[0])
print(np.argmax(predictions[1]))
print(predictions[1])
print(np.argmax(predictions[2]))
print(predictions[2])

1
[0.36671272 0.4011414  0.23214592]
0
[0.4766274  0.3515341  0.17183858]
0
[0.5020305  0.4385055  0.05946407]
